apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  params:
    - name: ref
      type: string
    - name: path
      type: string
      default: $(resources.inputs.source-repo.path)
  resources:
    inputs:
      - name: source-repo
        type: git
  steps:
    - name: dockertag-create
      workingDir: "$(params.path)"
      image: alpine/git:v2.24.3
      script: |
        #!/bin/sh
        pwd
        git rev-parse --short HEAD > git_sha
        git rev-parse --short HEAD
        echo $(resources.inputs.source-repo.path)
        echo $(params.ref)