apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  params:
  - name: ref
    type: string
  - name: sha
    type: string
  - name: path
    type: string
    default: $(resources.inputs.source-repo.path)
  - name: dockerRegistry
    type: string
    default: pprach/test
  resources:
    inputs:
    - name: source-repo
      type: git
  steps:
  - image: docker:dind
    name: dockerfile-build
    resources: {}
    script: |
      #!/usr/bin/env sh
      docker build -t $(params.dockerRegistry):$(params.sha) .
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
    workingDir: $(params.path)
  - image: docker:dind
    name: dockerimage-push
    resources: {}
    script: |
      #!/usr/bin/env sh
      docker push $(params.dockerRegistry):$(params.sha)
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
    workingDir: $(params.path)
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: Socket
    name: docker-socket