apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: update-config
spec:
  params:
    - name: ref
      type: string
    - name: sha
      type: string
    - name: path
      type: string
      default: $(resources.inputs.config-repo.path)
  resources:
    inputs:
      - name: config-repo
        type: git
  steps:
    - name: update-config 
      image: alpine/git:v2.24.3
      workingDir: "$(params.path)"
      env:
      - name: secret_env
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: token      
      script: |
        #!/usr/bin/env sh
        branch=$(echo "$(params.ref)" | awk -F '/' '{print $3}')
        if [ "$branch" = "develop" ] ; then
          git config --global user.email bot.github@pprach.pl
          git config --global user.name "Github Bot pprach"
          git checkout -b develop
          sed -i '9s/.*/  version: "$(params.sha)"/' helm/gotest/dev.yaml
          git add .
          git commit -m "push from pipeline"
          git push https://pprach:$secret_env@github.com/pprach/gotest_infra.git develop > /dev/null 0>&1 2>&1
          echo "Pushed to git"
        else
          echo "Nothing to do. Bye!"
        fi;
