apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-build-pipeline
spec:
  params:
  - name: ref
    type: string
  - name: sha
    type: string
  - name: eventtype
    type: string
  - name: commentsurl
    type: string
  resources:
  - name: source-repo
    type: git
  - name: config-repo
    type: git
  tasks:
  - name: build-app-dockerimage
    params:
    - name: ref
      value: $(params.ref)
    - name: sha
      value: $(params.sha)
    resources:
      inputs:
      - name: source-repo
        resource: source-repo
    taskRef:
      kind: Task
      name: build-task
  - name: update-config
    params:
    - name: ref
      value: $(params.ref)
    - name: sha
      value: $(params.sha)
    - name: eventtype
      value: $(params.eventtype)
    - name: commentsurl
      value: $(params.commentsurl)
    resources:
      inputs:
      - name: config-repo
        resource: config-repo
    runAfter:
    - build-app-dockerimage
    taskRef:
      kind: Task
      name: update-config
