apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-pipeline-template
spec:
  params:
  - name: gitrevision
  - name: gitrepositoryurl
  - name: gitref
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: trigger-pipeline-run-
    spec:
      pipelineRef:
        name: app-build-pipeline
#      params:
#      - name: message
#        value: $(params.message)
#      - name: contenttype
#        value: $(params.contenttype)
      resources:
      - name: source-repo
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.gitrevision)
          - name: url
            value: $(params.gitrepositoryurl)
      params:
      - name: ref
        value: $(params.gitref)