apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-my
spec:
  serviceType: NodePort
  serviceAccountName: default
  triggers:
    - name: my-trig
      bindings:
        - name: pipeline-binding
      template:
        name: trigger-pipeline-template